# Generated by Django 5.2.11 on 2026-05-12 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hotel', models.CharField(default='Hotel Real Palace', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('descripcion_principal', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
            ],
            options={
                'verbose_name': 'Configuración del Hotel',
                'verbose_name_plural': 'Configuración del Hotel',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('sencilla', 'Sencilla'), ('doble', 'Doble'), ('suite', 'Suite'), ('jacuzzi', 'Jacuzzi'), ('presidencial', 'Presidencial')], default='sencilla', max_length=20)),
                ('descripcion', models.TextField()),
                ('precio_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacidad', models.IntegerField(default=2)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='habitaciones/')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='★', max_length=10)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='✓', max_length=50)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='hotel_app.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='habitaciones/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='hotel_app.habitacion')),
            ],
        ),
    ]
